import mysql from 'mysql2/promise';
import dotenv from 'dotenv';

dotenv.config();

/**
 * Try to enable S3 using the auto-generated role ARN
 */

async function tryAutoGeneratedRole() {
  console.log('\n' + '='.repeat(80));
  console.log('🔍 TRYING AUTO-GENERATED ROLE FOR S3 INTEGRATION');
  console.log('='.repeat(80) + '\n');

  const DB_HOST = process.env.DB_HOST;
  const DB_USER = process.env.DB_USER;
  const DB_PASSWORD = process.env.DB_PASSWORD;
  const DB_NAME = process.env.DB_NAME;
  
  // Auto-generated role ARN (from RDS Console)
  const AUTO_ROLE_ARN = 'arn:aws:iam::357058555433:role/rds-s3-hotelbed-aurora-cluster-role-1762135258692';
  const MANUAL_ROLE_ARN = 'arn:aws:iam::357058555433:role/AuroraS3AccessRole';

  let connection: mysql.Connection | null = null;

  try {
    console.log('🔌 Connecting to Aurora...');
    connection = await mysql.createConnection({
      host: DB_HOST,
      port: parseInt(process.env.DB_PORT || '3306'),
      user: DB_USER,
      password: DB_PASSWORD,
      database: DB_NAME,
    });
    console.log('✅ Connected!\n');

    // Check procedure
    console.log('1️⃣  CHECKING PROCEDURE...\n');
    const [procRows]: any = await connection.query(
      `SELECT ROUTINE_NAME 
       FROM information_schema.ROUTINES 
       WHERE ROUTINE_SCHEMA = 'mysql' 
       AND ROUTINE_NAME = 'rds_add_s3_integration_role'`
    );

    if (procRows.length === 0) {
      console.log('   ❌ Procedure still NOT found\n');
      console.log('⚠️  Even with auto-generated role, procedure not loading!\n');
      console.log('🔧 SOLUTION: Use Manual AuroraS3AccessRole Instead\n');
      console.log('Steps:');
      console.log('1. RDS Console → Delete auto-generated role');
      console.log('2. Add AuroraS3AccessRole manually');
      console.log('3. Reboot instance');
      console.log('4. Check procedure again\n');
      process.exit(1);
    }

    console.log('   ✅ Procedure EXISTS!\n');

    // Try auto-generated role first
    console.log('2️⃣  TRYING AUTO-GENERATED ROLE...\n');
    console.log(`   Role ARN: ${AUTO_ROLE_ARN}\n`);

    try {
      await connection.query(
        `CALL mysql.rds_add_s3_integration_role(?)`,
        [AUTO_ROLE_ARN]
      );
      console.log('   ✅ S3 integration enabled with auto-generated role!\n');
    } catch (error: any) {
      if (error.message.includes('already')) {
        console.log('   ℹ️  Already enabled (OK)\n');
      } else {
        console.log(`   ❌ Error: ${error.message}\n`);
        console.log('   Trying manual role instead...\n');
        
        // Try manual role
        console.log('3️⃣  TRYING MANUAL ROLE...\n');
        console.log(`   Role ARN: ${MANUAL_ROLE_ARN}\n`);
        
        try {
          await connection.query(
            `CALL mysql.rds_add_s3_integration_role(?)`,
            [MANUAL_ROLE_ARN]
          );
          console.log('   ✅ S3 integration enabled with manual role!\n');
        } catch (manualError: any) {
          console.log(`   ❌ Error: ${manualError.message}\n`);
          throw manualError;
        }
      }
    }

    // Verify
    console.log('4️⃣  VERIFYING S3 INTEGRATION...\n');
    try {
      const [s3Rows]: any = await connection.query('SELECT * FROM mysql.aws_s3_integration');
      
      if (s3Rows.length > 0) {
        console.log('   ✅ S3 Integration verified!\n');
        console.table(s3Rows);
        
        // Check variables
        const [vars]: any = await connection.query(
          `SHOW VARIABLES WHERE Variable_name IN ('aurora_load_from_s3_role', 'aws_default_s3_role')`
        );
        console.log('\n   S3 Variables:');
        console.table(vars);
        
        console.log('\n' + '='.repeat(80));
        console.log('✅ SUCCESS! S3 INTEGRATION ENABLED!');
        console.log('='.repeat(80));
        console.log('\n📋 Next Steps:');
        console.log('   1. Test: npm run test-s3-aurora');
        console.log('   2. Run import: curl http://localhost:5000/api/v1/hotelbed/process\n');
      } else {
        console.log('   ⚠️  Table exists but is empty\n');
      }
    } catch (verifyError: any) {
      if (verifyError.message.includes("doesn't exist")) {
        console.log('   ⚠️  Table does not exist\n');
      } else {
        console.log(`   ⚠️  Error: ${verifyError.message}\n`);
      }
    }

  } catch (error: any) {
    console.error('\n❌ Error:', error.message);
    console.error('\n🔧 Alternative Solution:');
    console.error('   1. RDS Console → Delete auto-generated role');
    console.error('   2. Manually add AuroraS3AccessRole');
    console.error('   3. Reboot instance');
    console.error('   4. Try again\n');
    process.exit(1);
  } finally {
    if (connection) {
      await connection.end();
    }
  }
}

tryAutoGeneratedRole();


