/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface AppSigninPayloadDTO {
  email: string;
  password: string;
}

export interface AppSignupPayloadDTO {
  dateofbirth: string;
  email: string;
  firstName: string;
  lastName: string;
  meta?: object;
  password: string;
  type: string;
  userName: string;
}
