/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface CreateCouplePayloadDTO {
  partnerName: string;
  privacySettings: string;
  weddingDate: string;
  weddingWebsiteUrl: string;
}

export interface UpdateCouplePayloadDTO {
  partnerName: string;
  privacySettings: string;
  weddingDate: string;
  weddingWebsiteUrl: string;
}
